### PR TITLE
[#176591026] Added new stage for deploying client SDK to NPM

### PR DESCRIPTION
**Pull request by gquadrati**
- [x] Added new stage for publishing cliend SDK to NPM in template

### CODE REVIEW

**Comment by balanza** [comment]
I did not make my mind on this yet. Should this be default for every function?

**Comment by gquadrati** [comment]
> I did not make my mind on this yet. Should this be default for every function?

Fro what I could see so far, most of the Azure Functions projects are triggered by HTTP requests, so I though it should be set as default, but yes, I got your point. 
If we add it here, other can decide whether to leave it or not, otherwise how can the make this decision?

**Comment by balanza** [comment]
Well, we ship a default OpenApi spec, it makes sense to ship the sdk as well 🤷 .

Side note: as the package name is not important, template users often forget to change it and they just leave the default `io-functions-template`. Which is ugly, but not a problem so far. As we're inferring a package name from it, it's now an issue.

I suggest we either leave the field blank or fill it with an invalid placeholder (ex: `<YOUR PACKAGE NAME>`), so that at lease we avoid publishing a package with the default name.

**Comment by gquadrati** [comment]
> Well, we ship a default OpenApi spec, it makes sense to ship the sdk as well 🤷 .
> 
> Side note: as the package name is not important, template users often forget to change it and they just leave the default `io-functions-template`. Which is ugly, but not a problem so far. As we're inferring a package name from it, it's now an issue.
> 
> I suggest we either leave the field blank or fill it with an invalid placeholder (ex: `<YOUR PACKAGE NAME>`), so that at lease we avoid publishing a package with the default name.

We can set as '@pagopa/<YOUR PACKAGE NAME>' to make everyone aware of the need of having the org name set up, what d you think?

**Comment by balanza** [comment]
fine for me

**Comment by gquadrati** [comment]
> > Well, we ship a default OpenApi spec, it makes sense to ship the sdk as well 🤷 .
> > Side note: as the package name is not important, template users often forget to change it and they just leave the default `io-functions-template`. Which is ugly, but not a problem so far. As we're inferring a package name from it, it's now an issue.
> > I suggest we either leave the field blank or fill it with an invalid placeholder (ex: `<YOUR PACKAGE NAME>`), so that at lease we avoid publishing a package with the default name.
> 
> We can set as '@pagopa/`<YOUR PACKAGE NAME>`' to make everyone aware of the need of having the org name set up, what do you think?

Done in PR #17

**Pull request merged**
